# Generated by Django 4.2.6 on 2024-03-16 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0002_alter_flatlocation_flat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='equipment',
            field=models.ManyToManyField(blank=True, related_name='flat', to='flat.equip'),
        ),
    ]
