# Generated by Django 4.2.6 on 2024-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0003_alter_flat_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatdetail',
            name='development_type',
            field=models.CharField(choices=[('House', 'Detached house'), ('Block', 'Block'), ('Tenement', 'Tenement house'), ('Rowhouse', 'Rowhouse'), ('SemiHouse', 'Semi-detached house'), ('Loft', 'Loft'), ('Apartment', 'Apartment house')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flatdetail',
            name='floor',
            field=models.CharField(choices=[('Zero', 'Ground floor'), ('First', '1 floor'), ('Second', '2 floor'), ('Third', '3 floor'), ('Fourth', '4 floor'), ('Fifth', '5 floor'), ('Sixth', '6 floor'), ('Seventh', '7 floor'), ('Eighth', '8 floor'), ('Ninth', '9 floor'), ('Higher', '> 9 floor')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flatdetail',
            name='heating',
            field=models.CharField(choices=[('District', 'District heating'), ('Gas', 'Gas heating'), ('Electric', 'Electric heating'), ('Boiler', 'Boiler'), ('Other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='flatdetail',
            name='rooms',
            field=models.CharField(choices=[('One', '1'), ('Two', '2'), ('Three', '3'), ('Four', '4'), ('Five', '5'), ('Six', '6'), ('Seven', '7'), ('Eight', '8'), ('Nine', '9'), ('Ten', '10'), ('More', 'more than 10')], max_length=30),
        ),
        migrations.AddConstraint(
            model_name='flat',
            constraint=models.CheckConstraint(check=models.Q(('price__gte', 0.0)), name='flat_price_range'),
        ),
    ]
