# Generated by Django 4.2.6 on 2024-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flat', '0004_alter_flatdetail_development_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equip',
            name='name',
            field=models.CharField(choices=[('fridge', 'Fridge'), ('dishwasher', 'Dishwasher'), ('tv', 'TV'), ('washer', 'Washing machine'), ('furniture', 'Furniture'), ('stove', 'Stove'), ('oven', 'Oven'), ('balcony', 'Balcony'), ('terrace', 'Terrace'), ('elevator', 'Elevator'), ('ac', 'Air conditioning')], max_length=30),
        ),
    ]
