version: '3.11'

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./rent_flat:/rent_flat
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1
