# Generated by Django 4.2.6 on 2024-06-23 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationtype',
            name='name',
            field=models.CharField(choices=[('Add', 'Created'), ('Del', 'Deleted'), ('Mod', 'Modified'), ('Mess', 'Message')], max_length=100),
        ),
    ]
