# Generated by Django 4.2 on 2024-02-09 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='notify.notificationtype'),
        ),
    ]
